apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-management
  namespace: kubernetes-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-management
  template:
    metadata:
      labels:
        app: kubernetes-management
    spec:
      containers:
        - name: kubernetes-management
          image: hephaestusmetrics/kubernetes-management:0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8097