apiVersion: v1
kind: PersistentVolume
metadata:
  name: hephaestus-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
          path: "/mnt/hephaestus-pv"
