apiVersion: v1
kind: Service
metadata:
  name: business-demo
  namespace: hephaestus-business
spec:
  selector:
    app: business-demo
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8099
      targetPort: 8099
      nodePort: 31124
